### DISCUSSION TITLE
How to implement?

### DISCUSSION THREAD

**Discussion by barbalex** [invertase/flutterfire_desktop#39] [Q&A] [answered]
The beta version seems to be published: https://pub.dev/packages/firebase_auth_desktop

But how would it be used?

**Comment by pr-Mais** [comment, marked as answer]
To use this plugin as FlutterFire's implementation for Desktop, add it to your app's `pubspec.yaml` along with the main plugin:
```yaml
dependencies:
  firebase_auth: ^3.3.4
  firebase_auth_desktop: ^0.1.1-dev.3
  firebase_core: ^1.10.6
  firebase_core_desktop: ^0.1.1-dev.3
```
