### ISSUE TITLE
🐛 [firebase_auth_desktop] project has build error because of new Firebase updates

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/flutterfire_desktop#96]
![image](https://user-images.githubusercontent.com/24459435/181824593-da9f3751-b37d-4bd0-9b50-eaa0deed2820.png)

It's not possible to run the example of `firebase_auth_desktop` because there are many builds errors. The build error are coming from the new Firebase versions.

**Comment by nilsreichardt** [comment]
![image](https://user-images.githubusercontent.com/24459435/181825600-2147ff01-7fad-46ed-8610-cdb1f0d44eff.png)

This is the reason for the low the pub.dev score.

**Comment by rebaz94** [comment]
I just fixed temporary by providing fake ```MultiFactorImpl``` and adding missing override
you can use it [here](https://github.com/rebaz94/flutterfire_desktop)
```yaml
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  firebase_core_desktop: ^1.0.1
  firebase_auth_desktop: #^1.0.1
    git:
      url: https://github.com/rebaz94/flutterfire_desktop.git
      path: ./packages/firebase_auth/firebase_auth_desktop
```
